# Generated by Django 2.1.7 on 2019-04-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20190423_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legend',
            name='author',
        ),
    ]
