# Generated by Django 2.1.7 on 2019-05-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legend',
            name='transactions_type',
            field=models.TextField(max_length=6),
        ),
    ]
