# Generated by Django 2.1.7 on 2019-06-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20190512_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legend',
            old_name='author',
            new_name='user',
        ),
    ]
